# 文件名: .github/workflows/trigger_on_external_build.yml
name: Trigger Kernel Build (Manual or Auto)

on:
  # 1. 自动触发：当 ShirkNeko/SukiSU-Ultra 仓库的 "Build Manager CI/CD" 工作流成功完成时
  workflow_run:
    workflows: ["Build Manager CI/CD"] # 确保此名称与外部工作流的 'name' 字段完全匹配
    repository: ShirkNeko/SukiSU-Ultra
    types:
      - completed

  # 2. 手动触发：允许通过 GitHub UI 手动启动此工作流
  workflow_dispatch:
    inputs:
      simulation_mode:
        description: "选择手动触发模式"
        required: true
        type: choice
        options:
          - standard_manual_trigger # 标准手动触发
          - simulate_successful_external_trigger # 模拟外部工作流成功触发
        default: standard_manual_trigger
      target_branch_override:
        description: "覆盖目标分支 (例如 main, dev)。留空则使用默认逻辑。"
        required: false
        type: string

jobs:
  trigger_kernel_workflow:
    name: Trigger Local Kernel Build

    # 此作业的运行条件：
    # - 如果是真实的外部工作流触发 (workflow_run)，并且它成功了。
    # - 或者，如果是手动触发 (workflow_dispatch)，则总是运行（脚本内部将根据 simulation_mode 处理逻辑）。
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest
    permissions:
      contents: read # 检出代码所需
      actions: write # 触发其他工作流所需 (gh workflow run)

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Process trigger and dispatch kernel build
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TRIGGER_PAT }} # 确保 PAT 具有 'workflow' 权限
        run: |
          TRIGGER_TYPE=""
          SIMULATING_EXTERNAL_SUCCESS=false

          # 判断触发类型和是否模拟
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            TRIGGER_TYPE="真实外部触发"
            echo "${TRIGGER_TYPE}: 监听到 ShirkNeko/SukiSU-Ultra 仓库的 'Build Manager CI/CD' 工作流成功完成。"
            echo "  触发者 (外部): ${{ github.event.workflow_run.actor.login }}"
            echo "  外部工作流运行 ID: ${{ github.event.workflow_run.id }}"
            echo "  外部工作流提交 SHA: ${{ github.event.workflow_run.head_sha }}"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            if [[ "${{ github.event.inputs.simulation_mode }}" == "simulate_successful_external_trigger" ]]; then
              TRIGGER_TYPE="模拟外部成功触发"
              SIMULATING_EXTERNAL_SUCCESS=true
              echo "${TRIGGER_TYPE}: 由 ${{ github.actor }} 手动触发，并模拟外部工作流成功场景。"
            else
              TRIGGER_TYPE="标准手动触发"
              echo "${TRIGGER_TYPE}: 由 ${{ github.actor }} 手动触发。"
            fi
            echo "  手动输入 simulation_mode: ${{ github.event.inputs.simulation_mode }}"
            if [[ -n "${{ github.event.inputs.target_branch_override }}" ]]; then
              echo "  手动输入 target_branch_override: ${{ github.event.inputs.target_branch_override }}"
            fi
          else
            echo "未知的触发类型: ${{ github.event_name }}"
            exit 1
          fi

          echo "" # 空行用于分隔日志
          echo "准备触发本地的内核构建工作流 'A编译内核'..."

          # 确定目标分支 (TARGET_REF)
          # 规则：
          # 1. 如果用户在手动触发时指定了 target_branch_override，则优先使用它。
          # 2. 如果是“标准手动触发”（非模拟），则使用当前触发此工作流的分支 (github.ref)。
          # 3. 如果是“真实外部触发”或“模拟外部成功触发”，则默认使用本仓库的 'main' 分支。
          TARGET_REF=""
          if [[ -n "${{ github.event.inputs.target_branch_override }}" && "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TARGET_REF="refs/heads/${{ github.event.inputs.target_branch_override }}"
            echo "使用手动覆盖的目标分支: ${TARGET_REF}"
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" && "$SIMULATING_EXTERNAL_SUCCESS" == "false" ]]; then
            TARGET_REF="${{ github.ref }}" # 例如 refs/heads/feature-branch or refs/tags/v1.0
            echo "标准手动触发，使用当前上下文分支/标签: ${TARGET_REF}"
          else
            # 对于真实外部触发或模拟外部成功触发，通常目标是主线
            TARGET_REF="refs/heads/main" # 假设你的目标工作流主要在 main 分支上
            echo "真实或模拟外部触发，使用默认目标分支: ${TARGET_REF}"
          fi
          
          echo "最终将在分支/标签 ${TARGET_REF} 上触发名为 'A编译内核' 的工作流。"
          echo "请确保名为 'A编译内核' (对应文件 build-kernel.yml) 的工作流确实存在于仓库 Celestials316/Build-your-own-kernel 的 ${TARGET_REF} 上。"

          # 执行触发命令
          if gh workflow run "A编译内核" --ref "${TARGET_REF}"; then
            echo "已成功发送触发命令给 'A编译内核' 工作流。"
          else
            echo "错误：发送触发命令给 'A编译内核' 工作流失败。"
            echo "请检查：目标工作流名称是否正确、是否存在于 ${TARGET_REF}、以及 PAT 权限。"
            exit 1 # 触发失败，明确退出
          fi

          echo "你可以在 Actions 标签页查看 'A编译内核' 工作流的运行状态。"