name: A编译内核

permissions:
  contents: write
  actions: write

on:
  # 手动触发配置
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        description: "选择 KernelSU"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "选择 ksu 分支"
        required: true
        type: choice
        options:
          - Stable(标准)
          - Dev(开发)
          - Other(其他/指定)
        default: Dev(开发)
      version:
        description: '自定义版本后缀，留空随机生成'
        required: false
        type: string
      use_zram:
        description: '是否开启增加更多ZRAM算法?'
        required: true
        type: boolean
        default: true
      use_kpm:
        description: '是否开启KPM功能?'
        required: true
        type: boolean
        default: true

  # 新增自动触发配置
  workflow_run:
    workflows: ["build-manager"]
    types: [completed]
    branches: [main]

jobs:
  prepare_version_string:
    runs-on: ubuntu-latest
    outputs:
      final_version: ${{ steps.generate_version.outputs.version_string }}
    steps:
      - name: Generate or Use Custom Version String
        id: generate_version
        env:
          USER_PROVIDED_VERSION: ${{ github.event.inputs.version }}
        run: |
          VERSION_TO_USE=""
          if [[ -n "$USER_PROVIDED_VERSION" ]]; then
            echo "使用用户提供的版本字符串: $USER_PROVIDED_VERSION"
            VERSION_TO_USE="$USER_PROVIDED_VERSION"
          else
            echo "未提供版本字符串，正在生成随机版本字符串..."
            FIXED_PART="-android14-11"
            PREFIX1="gd"
            PREFIX2="ab"
            RANDOM_HEX=$(head /dev/urandom | LC_ALL=C tr -dc 'a-f0-9' | head -c 11 || true)
            RANDOM_DIGITS=$(head /dev/urandom | LC_ALL=C tr -dc '0-9' | head -c 8 || true)
            VERSION_TO_USE="${FIXED_PART}-${PREFIX1}${RANDOM_HEX}-${PREFIX2}${RANDOM_DIGITS}"
            echo "生成的随机版本字符串: $VERSION_TO_USE"
          fi
          echo "version_string=${VERSION_TO_USE}" >> "$GITHUB_OUTPUT"

  build-kernel-a14-6-1:
    needs: [prepare_version_string]
    # 添加自动触发时的参数处理
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    uses: ./.github/workflows/kernel-a14-6.1.yml
    secrets: inherit
    with:
      make_release: false
      # 根据触发类型选择参数来源
      kernelsu_variant: ${{ github.event.inputs.kernelsu_variant || 'SukiSU' }}
      kernelsu_branch: ${{ github.event.inputs.kernelsu_branch || 'Dev(开发)' }}
      version: ${{ needs.prepare_version_string.outputs.final_version }}
      use_zram: ${{ github.event.inputs.use_zram || true }}
      use_kpm: ${{ github.event.inputs.use_kpm || true }}
