name: A编译内核

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        description: "选择 KernelSU"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "选择 ksu 分支"
        required: true
        type: choice
        options:
          - Stable(标准)
          - Dev(开发)
          - Other(其他/指定)
        default: Dev(开发)
      version:
        description: '自定义版本后缀，留空随机生成'
        required: false
        type: string
      use_zram:
        description: '是否开启增加更多ZRAM算法?'
        required: true
        type: boolean
        default: true
      use_kpm:
        description: '是否开启KPM功能?'
        required: true
        type: boolean
        default: true

  schedule:
    - cron: '0 * * * *'  # 每小时检查一次

jobs:
  check_upstream_build:
    runs-on: ubuntu-latest
    outputs:
      should_continue: ${{ steps.check.outputs.should_continue }}
    steps:
      - name: Check last run of upstream build workflow
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          owner="ShirkNeko"
          repo="SukiSU-Ultra"
          workflow_id="build-manager.yml"

          response=$(curl -s -H "Authorization: Bearer $GH_TOKEN" \
            "https://api.github.com/repos/$owner/$repo/actions/workflows/$workflow_id/runs?per_page=1")

          last_status=$(echo "$response" | jq -r '.workflow_runs[0].status')
          last_conclusion=$(echo "$response" | jq -r '.workflow_runs[0].conclusion')

          echo "Upstream status: $last_status"
          echo "Upstream conclusion: $last_conclusion"

          if [[ "$last_status" == "completed" && "$last_conclusion" == "success" ]]; then
            echo "✅ 检测到成功的上游构建，继续执行"
            echo "should_continue=true" >> "$GITHUB_OUTPUT"
          else
            echo "⚠️ 上游构建未完成或失败，跳过"
            echo "should_continue=false" >> "$GITHUB_OUTPUT"
          fi

  prepare_version_string:
    needs: check_upstream_build
    if: github.event_name == 'workflow_dispatch' || needs.check_upstream_build.outputs.should_continue == 'true'
    runs-on: ubuntu-latest
    outputs:
      final_version: ${{ steps.generate_version.outputs.version_string }}
    steps:
      - name: Generate or Use Custom Version String
        id: generate_version
        env:
          USER_PROVIDED_VERSION: ${{ github.event.inputs.version }}
        run: |
          VERSION_TO_USE=""
          if [[ -n "$USER_PROVIDED_VERSION" ]]; then
            echo "使用用户提供的版本字符串: $USER_PROVIDED_VERSION"
            VERSION_TO_USE="$USER_PROVIDED_VERSION"
          else
            echo "未提供版本字符串，正在生成随机版本字符串..."
            FIXED_PART="-android14-11"
            PREFIX1="gd"
            PREFIX2="ab"
            RANDOM_HEX=$(head /dev/urandom | LC_ALL=C tr -dc 'a-f0-9' | head -c 11 || true)
            RANDOM_DIGITS=$(head /dev/urandom | LC_ALL=C tr -dc '0-9' | head -c 8 || true)
            VERSION_TO_USE="${FIXED_PART}-${PREFIX1}${RANDOM_HEX}-${PREFIX2}${RANDOM_DIGITS}"
            echo "生成的随机版本字符串: $VERSION_TO_USE"
          fi
          echo "version_string=${VERSION_TO_USE}" >> "$GITHUB_OUTPUT"

  build-kernel-a14-6-1:
    needs: [prepare_version_string]
    if: needs.prepare_version_string.result == 'success'
    uses: ./.github/workflows/kernel-a14-6.1.yml
    secrets: inherit
    with:
      make_release: false
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ needs.prepare_version_string.outputs.final_version }}
      use_zram: ${{ inputs.use_zram }}
      use_kpm: ${{ inputs.use_kpm }}
