name: A编译内核

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      kernelsu_variant:
        description: "选择 KernelSU"
        required: true
        type: choice
        options:
          - Official
          - Next
          - MKSU
          - SukiSU
        default: SukiSU
      kernelsu_branch:
        description: "选择 ksu 分支"
        required: true
        type: choice
        options:
          - Stable(标准)
          - Dev(开发)
          - Other(其他/指定) 
        default: Dev(开发)
      version_type:
        description: "版本后缀生成方式"
        required: true
        type: choice
        options:
          - 自定义 
          - 随机生成 
        default: 随机生成
      custom_version_suffix:
        description: '若选"自定义",在此输入后缀'
        required: false
        type: string
        default: "" 
      use_zram: 
        description: '是否开启增加更多ZRAM算法?'
        required: true
        type: boolean
        default: true
      use_kpm: 
        description: '是否开启KPM功能?'
        required: true
        type: boolean
        default: true

jobs:
  prepare-version: 
    runs-on: ubuntu-latest
    outputs:
      version_suffix_value: ${{ steps.version_generator.outputs.version_value }}
    steps:
      - name: Generate Version Suffix
        id: version_generator
        shell: bash
        env:
          INPUT_VERSION_TYPE: ${{ inputs.version_type }}
          INPUT_CUSTOM_SUFFIX: ${{ inputs.custom_version_suffix }}
        run: |
          set -x 
          VERSION_OUTPUT=""

          if [[ "$INPUT_VERSION_TYPE" == "自定义" ]]; then
            VERSION_OUTPUT="$INPUT_CUSTOM_SUFFIX" 
          elif [[ "$INPUT_VERSION_TYPE" == "随机生成" ]]; then
            # --- 恢复原始随机生成逻辑 ---
            FIXED_PART="-android14-11" 
            PREFIX1="gd"
            PREFIX2="ab"
            RANDOM_HEX=$( (LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c 11 | cat) || true )
            RANDOM_DIGITS=$( (LC_ALL=C tr -dc '0-9' < /dev/urandom | head -c 8 | cat) || true )
            VERSION_OUTPUT="${FIXED_PART}-${PREFIX1}${RANDOM_HEX}-${PREFIX2}${RANDOM_DIGITS}"
            # --- 原始逻辑结束 ---
          else
            VERSION_OUTPUT=""
          fi
          
          echo "version_value=${VERSION_OUTPUT}" >> "$GITHUB_OUTPUT"

  build-kernel-a14-6-1:
    needs: prepare-version 
    uses: ./.github/workflows/kernel-a14-6.1.yml
    secrets: inherit
    with:
      make_release: false 
      kernelsu_variant: ${{ inputs.kernelsu_variant }}
      kernelsu_branch: ${{ inputs.kernelsu_branch }}
      version: ${{ needs.prepare-version.outputs.version_suffix_value }} 
      use_zram: ${{ inputs.use_zram }} 
      use_kpm: ${{ inputs.use_kpm }}
