name: Cleanup Old Workflow Runs (中文名：清理旧的工作流运行记录)

on:
  schedule:
    - cron: '0 */24 * * *' # 每天的UTC时间00:00执行
  workflow_dispatch:

jobs:
  cleanup_runs:
    name: Keep Latest 5 Runs Per Workflow (中文名：每个工作流保留最新的5次运行)
    runs-on: ubuntu-latest
    permissions:
      actions: write

    steps:
      - name: Delete old workflow runs (中文名：删除旧的工作流运行记录)
        # 尝试使用更具体的版本标签，例如 v4.2.0 (请检查最新版本)
        uses: actions/delete-workflow-runs@v4.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain-days: 0
          keep-minimum-runs: 5
          # dry-run: true # 测试时可以取消注释