# 文件名: .github/workflows/kernel-a14-6.1.yml (或者您实际使用的文件名)
name: kernel-a14-6.1
permissions:
  contents: write
  actions: write

on:
  workflow_call:
    inputs:
      make_release:
        required: true
        type: boolean
        default: true
      kernelsu_variant:
        required: true
        type: string
        default: Next
      kernelsu_branch:
        required: true
        type: string
        default: Stable
      version:
        required: false
        type: string
        default: ""
      use_zram:
        description: '是否开启增加更多ZRAM算法?'
        required: true
        type: string     # <--- 类型是 string (正确)
        default: "true"  # <--- 默认值是字符串 "true" (正确)
      use_kpm:
        description: '是否开启KPM功能?'
        required: true
        type: string     # <--- 类型是 string (正确)
        default: "true"  # <--- 默认值是字符串 "true" (正确)

jobs:
  build-kernel-a14-6-1-kernelsu-susfs: # 这个作业名可以保持，或者您按需修改
    strategy:
      fail-fast: false
      matrix:
        include:
          - sub_level: "75" # 您可以按需保留或修改 matrix
            os_patch_level: "2024-05"
    uses: ./.github/workflows/gki-kernel.yml # 调用底层的 gki-kernel.yml
    secrets: inherit
    with:
      make_release: ${{ inputs.make_release }} # 布尔值直接透传
      android_version: "android14"             # 固定值或来自输入
      kernel_version: "6.1"                  # 固定值或来自输入
      sub_level: ${{ matrix.sub_level }}
      os_patch_level: ${{ matrix.os_patch_level }}
      kernelsu_variant: ${{ inputs.kernelsu_variant }} # 字符串直接透传
      kernelsu_branch: ${{ inputs.kernelsu_branch }}   # 字符串直接透传
      version: ${{ inputs.version }}                 # 字符串直接透传
      use_zram: ${{ inputs.use_zram }}                 # <--- 将接收到的字符串 use_zram 透传 (正确)
      use_kpm: ${{ inputs.use_kpm }}                   # <--- 将接收到的字符串 use_kpm 透传 (正确)