name: Test Gist Action Download by SHA
on: workflow_dispatch
jobs:
  test_download_job:
    runs-on: ubuntu-22.04 # 或者 ubuntu-latest
    steps:
      - name: Attempt to download peter-evans/gist-action by SHA
        uses: peter-evans/gist-action@2492b252f7530ab06305203605928330400382a5 # v3.1.0 的 commit SHA
        with:
          gist_id: 'a0f4a08491267936039c95997f913998' # 一个公共Gist ID
      - run: echo "Test action step was reached."