name: Test Other Peter Evans Action
on: workflow_dispatch
jobs:
  test_other_action:
    runs-on: ubuntu-latest
    steps:
      - name: Attempt to download peter-evans/create-pull-request
        uses: peter-evans/create-pull-request@v6
      - run: echo "Other test action step was reached."